#!/bin/sh


sudo docker cp pagesForDocker/site2.php  ksp_server:/var/www/html
sudo docker cp pagesForDocker/site1.php  ksp_server:/var/www/html
sudo docker cp pagesForDocker/site.php  ksp_server:/var/www/html
sudo docker cp pagesForDocker/index.php ksp_server:/var/www/html
sudo docker cp src/ass_res.php ksp_server:/var/www/html/assessment_result.php
sudo docker cp resources ksp_server:/var/www/html
sudo docker cp uploads ksp_server:/var/www/html
