#!/bin/sh


sudo docker cp pagesForDocker/site2.php  ksp_server:/var/www/html
sudo docker cp pagesForDocker/site1.php  ksp_server:/var/www/html
sudo docker cp pagesForDocker/site.php  ksp_server:/var/www/html
sudo docker cp pagesForDocker/index.php ksp_server:/var/www/html
sudo docker cp style.css ksp_server:/var/www/html
sudo docker cp KSP_Test ksp_server:/var/www/html
sudo docker cp compilers ksp_server:/var/www/html
sudo docker cp picture ksp_server:/var/www/html
sudo docker cp resources ksp_server:/var/www/html
sudo docker cp uploads ksp_server:/var/www/html
sudo docker cp upload.php ksp_server:/var/www/html
sudo docker cp upload1.php ksp_server:/var/www/html
sudo docker cp upload2.php ksp_server:/var/www/html
sudo docker cp ass_res.php ksp_server:/var/www/html/assessment_result.php
