#!/bin/bash

## copy steps

echo -e "<?php \n echo '" > .begin
echo -e "'; \n ?>" > .end

sed  "s/<?php/';/g" src/site2.php | sed "s/?>/echo '/g" > .tmp2

cat .begin src/site1.php .end > pagesForDocker/site1.php
cat .begin .tmp2 .end > pagesForDocker/site2.php
cat .begin src/site3.php .end > pagesForDocker/site3.php
cat .begin src/homepage.php .end > pagesForDocker/index.php
cat .begin src/about.php .end > pagesForDocker/about.php
cat .begin src/contact.php .end > pagesForDocker/contact.php
cat .begin src/help.php .end > pagesForDocker/help.php

rm .begin .end .tmp2 2>/dev/null

## docker steps

sudo docker run -d --rm -p 5000:80 --name ksp_server -v /var/www/html php:7.2-apache
#sudo docker run -d --rm -p 5000:80 --name ksp_server -v /var/www/html php:7.2-apache

[ ! -x "copyTotheDocker" ] && chmod a+x "copyTotheDocker"

[ $# -eq 0 ] && ./copyTotheDocker 2>/dev/null

[ $# -eq 0 ] && sudo docker exec ksp_server chmod -R 777 /var/www/html

echo "ther ksp_server is available on the adress:=  localhost:5000"
