#!/bin/bash

echo -e "<?php \n echo '" > .begin
echo -e "'; \n ?>" > .end

sed  "s/<?php/';/g" site2.php | sed "s/?>/echo '/g" > .tmp2

cat .begin site1.php .end > pagesForDocker/site1.php
cat .begin .tmp2 .end > pagesForDocker/site2.php
cat .begin site3.php .end > pagesForDocker/site3.php
cat .begin homepage.php .end > pagesForDocker/index.php

rm .begin .end .tmp2 2>/dev/null

sudo docker run -tid --rm -p 5000:80 --name ksp_server -v /var/www/html php:7.2-apache

[ $# -eq 0 ] && ./copyTotheDocker 2>/dev/null

[ $# -eq 0 ] && sudo docker exec ksp_server chmod -R 777 /var/www/html
