#!/bin/bash

## copy steps

echo -e "<?php \n echo '" > .begin
echo -e "<?php \n" > .begin1
echo -e "echo '" > .begin2
echo -e "'; \n ?>" > .end
#echo -e "'; \n" > .endI1
#echo -e "?>" > .endI2
#sed  "s/<?php/';/g" src/site2.php | sed "s/?>/echo '/g" > .tmp2

cat .begin src/site1.php .end > pagesForDocker/site1.php
cat .begin src/site2.php .end > pagesForDocker/site2.php
cat .begin src/site3.php .end > pagesForDocker/site3.php
cat .begin1 src/customerCounter .begin2 src/homepage.php .end > pagesForDocker/index.php
cat .begin src/about.php .end > pagesForDocker/about.php
cat .begin src/contact.php .end > pagesForDocker/contact.php
cat .begin src/help.php .end > pagesForDocker/help.php

rm .begin .end .tmp2 .begin1 .begin2 2>/dev/null

cp src/ass_res.php pagesForDocker/assessment_result.php

## docker steps
sudo docker -v 1>&2 2>/dev/null
[ $? -ne 0 ] && echo "You need to install docker before you can deploy the app !" && exit 0

[ "$1" != "start" ] && [ -e "Dockerfile" ] && sudo docker build -t ghcr.io/kowalski2019/ksp_tester_img:latest -f Dockerfile .
[ "$1" == "build" ] && echo "KSP-Tester image succeddfully built" && exit 0

[ $# -eq 1 ] || [ $# -eq 0 ] && sudo docker run -d --restart=always -p 5000:80 --name ksp_server ghcr.io/kowalski2019/ksp_tester_img:latest && \
	echo "the ksp_server is available on the address:=  localhost:5000/src"
